title: Visor Urbano
description: Bienvenido a la documentación de Visor Urbano
theme: just-the-docs

url: https://basicavisual.github.io/visor-urbano-docs

aux_links:
  Template Repository: https://github.com/basicavisual/visor-urbano-docs?tab=readme-ov-file
nav_enabled: true